### ISSUE TITLE
FTBS: latest r.cf20da3 qlipper fails to build on Linux Mint 18.2 - no matching function

### ISSUE THREAD

**Issue by Corin-EU** [pvanek/qlipper#72]
On Linux Mint 18.2 (based on Ubuntu LTS 16.04) with

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

and

Package: qtbase5-dev
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Architecture: i386
Multi-Arch: same
Source: qtbase-opensource-src
Version: 5.5.1+dfsg-16ubuntu7.5

qlipper fails to build with an error in qlippersystray.cpp

      In constructor 'QlipperSystray::QlipperSystray(QObject*)':
      /srv/repository/git/qlipper/src/qlippersystray.cpp:44:51: error: no matching function for call to
     'QMenu::addAction(QIcon, QString, QlipperModel*&, void (QlipperModel::*)())'
      , m_model, &QlipperModel::clearHistory);

and 

       /usr/include/i386-linux-gnu/qt5/QtWidgets/qmenu.h:76:14: note: candidate:
       QAction*   QMenu::addAction(const QString&)
        QAction *addAction(const QString &text);
              ^ 
        /usr/include/i386-linux-gnu/qt5/QtWidgets/qmenu.h:76:14: note:
       candidate expects 1 argument, 4 provided

Full details in attached text file log.

[error.txt](https://github.com/pvanek/qlipper/files/1209979/error.txt)

**Comment by palinek** [comment]
Right... we need at least Qt v5.6... added the required version into CMakeLists.txt -> 6753c3fdfd2c3273bb6551212819d7200400e570

**Comment by Corin-EU** [comment]
Thanks for the explanation and the added requirement to the CMakeLists.txt file.
